services:
  - type: web
    name: rendiciones
    runtime: python
    plan: free
    repo: https://github.com/tizianodistribuidoraacero-stack/rendiciones
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
